excluded:
  - Pods
  - Cosmos/Data Sources/DiscoverDataSource.swift
  - Cosmos/Data Sources/FavoritesDataSource.swift

# Rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo

# Minimum line length
line_length: 240

# Minimum parameter count
function_parameter_count: 6

# Minimum identifier length
identifier_name:
  min_length: 2
