name: Build & Test

on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build & Test

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Get Xcode version
      run: xcodebuild -version
      
    - name: Install dependencies
      run: pod install
      
    - name: Build
      run: xcodebuild clean build-for-testing -workspace Cosmos.xcworkspace -scheme "Cosmos" -destination "name=iPhone 11 Pro,OS=13.2.2"
    
    - name: Test
      run: xcodebuild test-without-building -workspace Cosmos.xcworkspace -scheme "Cosmos" -destination "name=iPhone 11 Pro,OS=13.2.2" -enableCodeCoverage=YES
