name: Build & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-10.14
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer

    steps:
    - uses: actions/checkout@v1
    - name: Build & run tests
      run: |
        xcodebuild -version
        pod install
        xcodebuild clean test -workspace Cosmos.xcworkspace -scheme "Cosmos" -destination "name=iPhone 11,OS=13.0"
